### PR TITLE
Use 'wp-scripts test-e2e' instead of directly calling jest

### PR DESCRIPTION
**Pull request by Aljullu**
Supersedes #1958 and it better aligns Storefront e2e tests with what we have in WC Blocks.

### How to test the changes in this Pull Request:

1. Make sure e2e tests pass in this PR.
2. Optionally, verify tests also pass locally:
2.1. Start docker.
2.2. Start wp-env: `npm run wp-end start`.
2.3. Build Storefront: `npm run build`.
2.4. Run tests: `npm run test:e2e`.
2.5. Verify all tests are a success.

### CODE REVIEW

**Review by tomasztunik — COMMENTED** [review]
looks good but wanted to confirm - do we still need after moving to wp-env the `jest-puppeteer` dependency and `jest` config on lines 63-71? https://github.com/woocommerce/storefront/blob/8b74758b402c5c6d32112e4134348c85c3fbf955/package.json#L63-L71

**Comment by Aljullu** [comment]
> looks good but wanted to confirm - do we still need after moving to wp-env the `jest-puppeteer` dependency and `jest` config on lines 63-71? https://github.com/woocommerce/storefront/blob/8b74758b402c5c6d32112e4134348c85c3fbf955/package.json#L63-L71

Yes, I think so. Because `wp-scripts test-e2e` internally calls Jest. At least, I couldn't get it to work when removing the config or `jest-puppeteer`.

**Comment by danielwrobert** [comment]
@Aljullu looks like the last activity on this PR was ~10 months ago. Is this still relevant?

I'd be happy to review it, if so. Otherwise I'll go ahead and close it out.

**Comment by Aljullu** [comment]
> @Aljullu looks like the last activity on this PR was ~10 months ago. Is this still relevant?

Ups, I completely forgot about it! While I don't think it's urgent, I do think it's worth merging it as it makes the Storefront e2e testing infrastructure closer to other projects like WC Blocks.

**Comment by danielwrobert** [comment]
> While I don't think it's urgent, I do think it's worth merging it as it makes the Storefront e2e testing infrastructure closer to other projects like WC Blocks.

No worries, I'll add it to my list to review today or tomorrow!

**Comment by danielwrobert** [comment]
Everything tests as described here all tests in this suite are passing locally. It looks like come ESLint checks are failing, however. I tried to re-run them and see if they'd pass but that didn't seem to help.

**Comment by Aljullu** [comment]
> Everything tests as described here all tests in this suite are passing locally. It looks like come ESLint checks are failing, however. I tried to re-run them and see if they'd pass but that didn't seem to help.

Right... they don't seem to be introduced by this PR, though. So not sure if this should block merging or not. :thinking:

**Review by danielwrobert — APPROVED** [review]
> Right... they don't seem to be introduced by this PR, though. So not sure if this should block merging or not. 🤔

Yeah, I imagine it's fine - the tests are passing and it doesn't seem that those failing checks are related, as you noted. I do see some more recent PRs where those are passing - perhaps a rebase will get them sorted out? If not, I think we can proceed with merging this and then file a follow-up issue to investigate the checks.

**Comment by Aljullu** [comment]
> perhaps a rebase will get them sorted out?

This branch is already up-to-date. Honestly, I'm not sure why those jobs are passing in other PRs because the fails seem legit.

In any case, I will go ahead and merge this PR as-is. We can work on the failing jobs in follow-ups.

**Pull request merged**
