### PR TITLE
correct typo in icons.scss

### PR DESCRIPTION
**Pull request by GlennMartin1**
correct typo in icons.scss

navigtion > navigation

### CODE REVIEW

**Comment by GlennMartin1** [comment]
I'm a novice at this, but I think https://github.com/woocommerce/storefront/issues/1333 is **not** referring to the the same code as this PR.

**Comment by Aljullu** [comment]
Why do you think so @GlennMartin1? Your PR is modifying `icons.scss`, after build (running `npm run build` in a terminal) it becomes `icons.css`. Line numbers change between them but that's to be expected. I checked line 4439 of `icons.css` and it matches the selector you modified in `icons.scss`, so I think they are the same. Does that make sense?

**Comment by GlennMartin1** [comment]
Ok, very well; I don't understand the build process. The reason for my confusion is this:

- This pull request targets this misspelling: `.main-navigtion`.
- But issue https://github.com/woocommerce/storefront/issues/1333 targets this misspelling `.main-navgation`.

Those are different misspellings.

**Comment by Aljullu** [comment]
Aaah, good catch @GlennMartin1. I think that's a typo in the issue description: `icons.css` L4439 is `.main-navigtion ul li a::before {` for me

**Comment by haszari** [comment]
> It seems that this has been broken for more than 3 years now, so I think most stores expect the icon not to appear. In my opinion, instead of fixing this we should plainly remove that block of CSS (L114-L126). How does it sound?

> Pinging @haszari for his opinion as well.

I agree with @Aljullu, if these icons have not been used for three years, it's probably not a great idea to add them back unless there's a request/report to do so. Looking at that screenshot it's not clear to me that these are useful - they just show a "document" icon for all nav options, which doesn't seem right.

Note there's a similar issue with icons in comments (#1319). In that case I'm leaning towards fixing it because the icons provide a clear benefit, and the fix won't change something so critical as the main nav/header.

So I'm thinking we tidy this css up - remove the broken rule for these icons, rather than fix it. Note we don't need to consider this for 2.6.1 :)

**Comment by haszari** [comment]
Closing this PR - as discussed above, we've decided not to pursue the fix.

Logged a new issue for removing the stale css, after appropriate investigation / testing: https://github.com/woocommerce/storefront/issues/1347

**Pull request closed without merging**
