### PR TITLE
Release 2.5.8

### PR DESCRIPTION
**Pull request by nerrad**
This is the release pull request for 2.5.8 of Storefront:

* [x] Changelog created.
* [x] Versions updated (rc.1)
* [x] RC tag published.
* [x] Changes tested.
* [x] Final versions updated 
* [x] Release tag published
* [x] Deployed to [WordPress](https://wordpress.org/themes/upload/)
* [x] Confirm WordPress.org version is correct and sites can auto-update.
* [x] Post announcement on dev blog.
* [x] Update [demo site](https://themes.woocommerce.com/storefront/)
     * [x] Clone/update [demo.woothemes.com](https://github.com/automattic/demo.woothemes.com) repository master branch.
     * [x] Update storefront – i.e. unzip and replace themes/storefront.
     * [x] Commit & push.
     * [x] Site should automatically build & deploy.

### CODE REVIEW

**Comment by nerrad** [comment]
Hit a snag while releasing on WordPress.org themes. It looks like the following are now _required_ in the `style.css` file:

- **Tested up to:**
- **Requires PHP:**

**Comment by nerrad** [comment]
Is deployed to WordPress.org and I've verified it made it [via trac](https://themes.trac.wordpress.org/browser/storefront/) but it's not showing up as ready for download yet (likely on a cron). So I'll monitor and resume once it populates in the listing.

**Comment by nerrad** [comment]
I committed to the demo site repo to get 2.5.8 added, but I don't know how to tell if it got deployed successfully. I can't log into the demo site backend and it doesn't look like there is any version info for Storefront as a meta tag.

So I've left those items unchecked for now.

Also, do we usually bump the version in the master branch for Storefront after everything is done?

**Comment by haszari** [comment]
Thanks @nerrad !

> I committed to the demo site repo to get 2.5.8 added, but I don't know how to tell if it got deployed successfully. I can't log into the demo site backend and it doesn't look like there is any version info for Storefront as a meta tag.

I think I usually confirm this by smoke-testing a newly fixed bug. But we should probably all have access to the demo site - thanks for raising that :) I can add you and other team members to the site - will follow up in Slack. Confirmed that it's running 2.5.8:

Screen Shot 2020-07-07 at 8 39 15 AM

> Also, do we usually bump the version in the master branch for Storefront after everything is done?

No specific requirement to do this as part of release process. Usually doesn't get updated until next RC - though we could improve this and update to `v.v.v-dev` after release.

**Pull request closed without merging**
