### PR TITLE
Update all dev dependencies using `ncu -a`

### PR DESCRIPTION
**Pull request by rodrigoprimo**
This PR updates all NPM dev dependencies using `ncu -a` (npm-check-updates).

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
After updating the packages running `npm run build` is generating a warning and a fatal error. I will try to find some time to investigate this. We will need to fix at least the fatal error before proceeding with this PR:

```
$ npm run build      

> grunt


  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


Running "stylelint:all" (stylelint) task
>> Linted 33 files without errors

Running "sass:dist" (sass) task
Fatal error: Error: no mixin named susy-media
        on line 84 of assets/css/woocommerce/extensions/wishlists.scss
>> @include susy-media($desktop) {

   ---------^
```

**Comment by haszari** [comment]
I'm looking at updating our dependencies in a separate PR - updating to latest minor version (this PR is more aggressive, updating everything to latest – including major versions). 

PR coming soon, the branch is here: https://github.com/woocommerce/storefront/tree/update/dev-dependencies

**Comment by haszari** [comment]
Closing this in favour of #1258 (now merged).

**Comment by rodrigoprimo** [comment]
Thanks for working on this, @haszari

**Pull request closed without merging**
