### PR TITLE
Remove Infinite scroll hacks

### LINKED ISSUE #781: Jetpack Infinite Scroll tweaks
Update `posts_per_page` to respect the number of products per page set in the Customizer. For WooCommerce version under 3.3, we can keep `12` as a default number, or perhaps use the legacy `products_per_page` method somehow.

Figure out why the "load more" button shows one last time after all products have been loaded.

cc @jeffikus

### PR DESCRIPTION
**Pull request by tiagonoronha**
Fixes #781.

### CODE REVIEW

**Comment by danieldudzic** [comment]
@tiagonoronha Thanks for working on this! I'll test it today. 🙏

**Comment by danieldudzic** [comment]
Did some preliminary testing, but can't confirm 100% that the fix works. I will do more extensive testing tomorrow and let you know.

**Comment by danieldudzic** [comment]
Posting here for posterity:

I’m still seeing the issue: http://g.recordit.co/z0wdlQKbHZ.gif

* I have 23 published products
* The Shop page displays 12
* The Customizer displays all 23

**Comment by danieldudzic** [comment]
@tiagonoronha 

http://dev-woocommerce-infinite-scroll.pantheonsite.io/ - running the fix/781 branch of Storefront

login: admin
password: temp123

**Comment by tiagonoronha** [comment]
The scope of this PR changed, as changes have been submitted to Jetpack and WooCommerce to enhance compatibility. 

Please read:

* https://github.com/Automattic/jetpack/pull/9112 
* https://github.com/Automattic/jetpack/pull/9120 
* https://github.com/woocommerce/woocommerce/pull/19477

**Comment by tiagonoronha** [comment]
I'm going to go ahead and merge this PR. By the time 2.3 is released, Jetpack will already be out, as well as the next time version of WooCommerce.

**Pull request merged**
