### PR TITLE
Add integration/support for WooCommerce Product Recommendations extension

### PR DESCRIPTION
**Pull request by franticpsyx**
### Description

This PR adds support for WooCommerce Product Recommendations. Changes:

* Add some sass definitions to properly style recommendations block headings.

PS: Please consider merging this into the next point release along with https://github.com/woocommerce/storefront/pull/1159, as the extension is very close to launch. Thanks!

### CODE REVIEW

**Comment by tiagonoronha** [comment]
@franticpsyx since Storefront 2.5 the homepage template is no longer the default.

A new page is created using Gutenberg blocks that is identical to the old template with the advantage that it can be edited directly in the editor.

https://docs.woocommerce.com/document/installation-configuration/#section-12

We don't want to encourage the use of this template anymore and it will eventually be removed.

Please let me know how you would like to proceed.

Thanks!

**Comment by franticpsyx** [comment]
Hey @tiagonoronha thanks for the heads-up!

> We don't want to encourage the use of this template anymore and it will eventually be removed.

Sounds great ;)

It doesn't make much sense to add any new functionality based on the `homepage` action, then! 

I've:

* removed all functionality relied on the `homepage` action;
* kept https://github.com/woocommerce/storefront/pull/1173/commits/ae52fde6e60e2a10f0ba1f83ca97eba5ecef3fec as it might be handy in support; and
* kept the new sass/css definitions for recommendation sections (necessary for consistency).

**Comment by tiagonoronha** [comment]
@franticpsyx please also remove ae52fde and keep only the CSS changes required for the extension. 

Also, I need access to the extension in order to test these changes before merging.

Thanks!

**Comment by franticpsyx** [comment]
@tiagonoronha Done and done!

**Comment by tiagonoronha** [comment]
@franticpsyx a couple requests:

* There's some CSS left related to the homepage logic that was removed. Please remove it.
* Instead of hard coding the values, could you please use the modular scale helper functions like we do in all other core files? For example, `ms(1)` will correspond to `1em`.

Thank you

**Comment by franticpsyx** [comment]
@tiagonoronha thank you for the heads-up! I believe we're done with the changes -- I'm afraid we didn't manage to see your message in time for 2.5.1 though. Any chance we can hope for a follow-up point release soon?

**Comment by tiagonoronha** [comment]
@franticpsyx 2.5.1 is not out yet, this will be there. :) 

Thank you!

**Pull request merged**
