### PR TITLE
hotfix header overlay-x

### PR DESCRIPTION
**Pull request by reatlat**
fix horisontal scroll on header part

### CODE REVIEW

**Comment by reatlat** [comment]
image

**Comment by jameskoster** [comment]
Which browser is this happening in? I thought we'd conquered this issue once and for all!

**Comment by reatlat** [comment]
Hmm I use Chromium Version 59.0.3071.104 (Developer Build) (64-bit)
Maybe it happened only for Linux users...

**Comment by jameskoster** [comment]
Interesting. And definitely latest Storefront version?

**Comment by reatlat** [comment]
No it was old version 2.1.8,
I just update to version 2.2.3
and problem is almost same without background but with horizontal scroll
image

**Comment by reatlat** [comment]
@jameskoster I just understand, this issue comes only then I resize a window screen.
I think it no big deal but sometimes users can resize a window and have a same issue...

**Comment by mikejolley** [comment]
Latest Storefront no longer has this overlay so the fix won't be needed.

Tested on mac chrome, firefox, linux chromium.

Thanks

**Comment by mikejolley** [comment]
Ah confirmed what this fixes on linux. Will cherry pick. Thanks.

**Pull request closed without merging**
