### PR TITLE
Header Cart Dropdown Scrolling

### PR DESCRIPTION
**Pull request by opportus**
Related to #479.

Actually, I'm not really experimented with JS, so take a close look... :P 
My main doubts are:

1. Does Storefront support Explorer 8 ? If so, I need to make it compatible...
2. Is the frontend behaviour OK ?
3. Is there a better approach ?

### CODE REVIEW

**Comment by jameskoster** [comment]
This is a different approach to what I had in mind, but maybe I didn't explain that clearly in the original issue.

I think the header cart contents should only scroll if the dropdown is tall enough to make the bottom of it disappear off-screen.

What I was going to do was;

* Get the window height
* Get the site header height
* Get the cart dropdown height

Then, if the site header height + the cart dropdown height > the window height then add the scrolling behaviour.

**Comment by opportus** [comment]
Hi @jameskoster 

It's what I've done... 😕

**Comment by jameskoster** [comment]
Ah, it would help if I remembered to compile the css when I test, it looked like it was always scrolling. Derp xD

I didn't actually know about `getBoundingClientRect()`, definitely looks like a nice shortcut. Browse support is fine and it'll degrade fine.

I'll merge this in.

**Comment by opportus** [comment]
Great !

**Pull request merged**
