### PR TITLE
Fix calls to deprecated method get_cart_url

### PR DESCRIPTION
**Pull request by pdewouters**

### CODE REVIEW

**Comment by jameskoster** [comment]
Cheers!

**Comment by claudiosanches** [comment]
@pdewouters @jameskoster 

A bug has been introduced here, there is no `WC()->cart->wc_get_cart_url()` method, the correct it's a function called `wc_get_cart_url()`.
Note that `WC()->cart->get_cart_url()` is soft deprecated and will not cause any issue or warning for now, but this Pull Request will result in a FATAL error, like:

```
PHP Fatal error:  Uncaught Error: Call to undefined method WC_Cart::wc_get_cart_url()
```

**Comment by pdewouters** [comment]
oh I apologize!

**Comment by jameskoster** [comment]
That's ok I fixed in https://github.com/woocommerce/storefront/commit/457fc1323d2a848dd71f506de1aa4fe81bf2a121

**Comment by pdewouters** [comment]
thanks, sorry for giving you extra work :(

**Comment by jameskoster** [comment]
No problem, really :)

**Pull request merged**
