### PR TITLE
Prevent image bleed from next image in the gallery

### PR DESCRIPTION
**Pull request by tiagonoronha**
Reported here: https://github.com/woocommerce/homestore/issues/35

### CODE REVIEW

**Comment by tiagonoronha** [comment]
This needs more work, the transition is ugly with the initial fix.

**Comment by tiagonoronha** [comment]
This issue is caused by Flexslider not correctly calculating the size of the container. We use percentages, and not a fixed value. In some specific cases, the calculation is off by about ~1px.

I tested and the fix doesn't seem to cause any other issues, I believe it is safe to merge.

**Comment by mikejolley** [comment]
Looks ok to me 👍

**Comment by dr1ftk1ng** [comment]
In my case i had to manually remove this fix, as it was causing the bleed.
I am running Woocommerce 3.3.3 with Storefront 2.2.8
I am not quite sure, but maybe the current Woocommerce version is using a fixed Flexslider version.

**Pull request merged**
