### PR TITLE
Translatable `aria-label`

### PR DESCRIPTION
**Pull request by andreaskian**
Improvement suggestion: remove hardcoded english texts causing unwanted result on multilingual site.

### CODE REVIEW

**Comment by jameskoster** [comment]
Rather than removing it, why not make it translatable?

https://codex.wordpress.org/Function_Reference/esc_attr_e

**Comment by andreaskian** [comment]
Hi James, 

I was simply not thinking of that – Sorry. I have tried to update my PR to use the `esc_html__()` function.

**Comment by andreaskian** [comment]
Do I need to update `/languages/storefront.pot` with my new translatable strings?

**Comment by jameskoster** [comment]
No problem. I think `esc_attr__()` might be the more appropriate function to use here though.

> Do I need to update /languages/storefront.pot with my new translatable strings?

No that's OK, our build tasks will take care of that when we release.

**Comment by andreaskian** [comment]
I've updated PR with `esc_attr__()` instead

**Comment by jameskoster** [comment]
Thank you! I'll merge this now.

**Pull request merged**
